[tool.isort]
profile = "black"
line_length = 200

[tool.autopep8]
max_line_length = 200
indent_size = 2

[tool.yapf]
based_on_style = "pep8"
indent_width = 2
continuation_indent_width = 2
indent_dictionary_value = false
allow_split_before_dict_value = false
join_multiple_lines = true
column_limit = 200
